title: "Er. Rohit Anand"
subtitle: "Researcher in Precision Agriculture | AI in Digital Farming"
description: >- 
  PhD Scholar & Graduate Research Associate at The Ohio State University. 
  Working in Precision Agriculture, Digital Farming, and AI-based Crop Monitoring.

author: Rohit Anand
email: anandrohit0621@gmail.com
avatar: /assets/img/profile.jpg  # (Add your photo there)
location: Columbus, USA
footer-links:
  email: anandrohit0621@gmail.com
  github: anandhub0621
  linkedin: https://www.linkedin.com/in/therohitanand/
  researchgate: https://www.researchgate.net/profile/Rohit-Anand-8?ev=hdr_xprf
  cv: /assets/files/Rohit_CV.pdf

navbar-links:
  About Me: "about"
  Research & Publications: "research"
  Curriculum Vitae: "cv"
  Blog: "blog"
  Contact: "contact"
