title: "Er. Rohit Anand"
description: >-
  Personal Website of Er. Rohit Anand | Researcher in Precision Agriculture, AI in Digital Farming, and Remote Sensing.
  Graduate Research Associate at The Ohio State University.

url: "https://anandhub0621.github.io"  # ← Replace with your actual GitHub Pages URL
baseurl: ""  # Keep it empty if it's your user/organization site (not a project site)

author:
  name: "Er. Rohit Anand"
  email: "anandrohit0621@email.com"
  location: "Columbus, USA"
  bio: "Researcher in Precision Agriculture, Digital Agriculture, and AI in Farming."
  avatar: "/assets/profile.jpg"  # Make sure this image exists

# Theme
theme: minima

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social links (optional but recommended for footer visibility)
social_links:
  linkedin: https://linkedin.com/in/therohitanand
  github: https://github.com/anandhub0621
  google_scholar: https://scholar.google.com/citations?user=za2Ac2AAAAAJ&hl=en
  researchgate: https://www.researchgate.net/profile/Rohit-Anand-8?ev=hdr_xprf

# Navigation menu
header_pages:
  - index.md
  - about.md
  - research.md
  - publications.md
  - contact.md
  - cv.md

# SEO settings (for better discoverability)
google_analytics: ""  # Add your GA ID if any
show_excerpts: true

# Feed settings
feed:
  path: feed.xml

# Minima Theme Colors (Optional)
minima:
  skin: auto  # auto | classic | dark | solarized
  social_links:
    - { platform: github,        user_url: "https://github.com/your-username" }
    - { platform: linkedin,      user_url: "https://linkedin.com/in/your-link" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/your-profile" }
    - { platform: researchgate,  user_url: "https://www.researchgate.net/profile/YourName" }

