title: "Er. Rohit Anand"
description: >-
  Personal Website | Researcher | Academic Portfolio | Blog
baseurl: ""  # Keep this empty for user.github.io site
url: "https://Anandhub0621.github.io"

theme: minima

author:
  name: Er. Rohit Anand
  email: your-email@example.com # Replace with your professional email (optional)
  avatar: "/assets/profile.jpg"   # Upload your photo in /assets/
  bio: "Researcher in Precision Agriculture | Digital Agriculture | Academic Writer"
  location: "Columbus, USA"
  email: "anandrohit0621@email.com"
  
# Social links (add or remove as needed)
social_links:
  github: anandhu0621
  linkedin: your-linkedin-username
  twitter: your-twitter-handle
  # other options: facebook, instagram, youtube, stackoverflow, etc.

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# SEO settings
google_analytics: UA-XXXXXXXXX-X # Replace with your tracking ID if you have one

# Header/footer customization
minima:
  skin: classic
  social_links:
    github: https://github.com/Anandhub0621
    linkedin: https://linkedin.com/in/therohitanand
  date_format: "%b %-d, %Y"

# Navigation links (update according to your content structure)
header_pages:
  - index.md
  - About.md
  - research.md
  - blog.md
  - contact.md
  - cv.md

# Optional: Markdown formatting
markdown: kramdown
kramdown:
  input: GFM

# Exclude files you don't want to publish
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
