# Website Basic Info
title: "Er. Rohit Anand"
email: anandrohit0621@email.com
description: >- 
  Personal Website | Researcher | Academic Portfolio | Blog
url: "https://Anandhubo621.github.io"
baseurl: ""  # Keep this empty for user.github.io site

# Author Information
author:
  name: "Er. Rohit Anand"
  avatar: "/assets/profile.jpg"   # Upload your photo in /assets/
  bio: "Researcher in Precision Agriculture | Digital Agriculture | Academic Writer"
  location: "Columbus, USA"
  email: "anandrohit0621@email.com"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:anandrohit0621@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/therohitanand"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=za2Ac2AAAAAJ&hl=en"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Anandhub0621"
    - label: "ResearchGate"
      icon: "fab fa-researchgate"
      url: "https://www.researchgate.net/profile/Rohit-Anand-8/research"

# Theme
theme: minima

# Build Settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# SEO
title_separator: "|"

# Navigation Menu
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

# Main Navigation Bar
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Research"
    url: /research/
  - title: "CV"
    url: /cv/
  - title: "Contact"
    url: /contact/
  - title: "Blog"
    url: /year-archive/

# Social Sharing Image (Optional)
# social:
#   image: /assets/banner.png

# Site Footer
